version: '3'
services:
  traffic-collision:
    image: mageai/mageai:latest
    container_name: traffic-collision
    command: mage start ${MAGE_PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${MAGE_PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
