version: '3'
services:
  openaq:
    image: mageai/mageai:latest
    container_name: openaq
    command: mage start mage-dbt
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/openaq/
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
