
version: 2

sources:
  - name: stg
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('BIGQUERY_DATASET') }}"
    tables:
      - name: stg_openaq_measurements
      - name: stg_openaq_locations
      - name: stg_openaq_parameters

models:
  - name: fact_measurements
    description: Fact table containing unique measurements. Can be joined with dim_locations, and dim_parameters.
    columns:
      - name: measurement_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: location_id
        description: "Location secondary key"
        tests:
           - accepted_values:
                values: "{{ var('locations') }}"
                severity: warn
      - name: parameter_id
        description: "Parameter seconday key"
      - name: measurement_average
        description: ""
      - name: measurement_count
        description: ""
  - name: dim_locations
    description: Dimensional table containing information about the measurement stations' location and coordinates.
    columns:
      - name: location_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: location_name
        description: "Location code name"
      - name: country
        description: ""
      - name: city
        description: ""
      - name: latitude
        description: ""
      - name: longitude
        description: ""
  - name: dim_parameters
    description: Dimensional table containing information about the parameters that are measured in the stations.
    columns:
      - name: parameter_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: parameter_code
        description: "Parameter identificator in lowercase"
      - name: parameter_name
        description: "Human readable parameter name"
      - name: description
        description: ""
      - name: unit
        description: ""