name: 'OpenAQ'
version: '1.0.0'
config-version: 2

profile: 'OpenAQ'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  OpenAQ:
    stg:
      +materialized: view

vars:
  locations: ['3265','3288','3353','3364','3367','4241','4244','4247','4248','4267','4270','4280','4281','4283','4288','4298','4305','4313','4332','4333','4338','4341']